/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sfs
 */
public class HRDepartment extends javax.swing.JFrame {

    /**
     * Creates new form HRDepartment
     */
    public HRDepartment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        agebg = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nametf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bt12 = new javax.swing.JRadioButton();
        bt14 = new javax.swing.JRadioButton();
        bt18 = new javax.swing.JRadioButton();
        bta18 = new javax.swing.JRadioButton();
        bt16 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        edulist = new javax.swing.JList();
        tvcb = new javax.swing.JCheckBox();
        artcb = new javax.swing.JCheckBox();
        wmcb = new javax.swing.JCheckBox();
        advcb = new javax.swing.JCheckBox();
        cookcb = new javax.swing.JCheckBox();
        indcb = new javax.swing.JCheckBox();
        playcb = new javax.swing.JCheckBox();
        othercb = new javax.swing.JCheckBox();
        subbtn = new javax.swing.JButton();
        canbtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        sublist = new javax.swing.JList();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Noto Sans", 3, 14)); // NOI18N
        jLabel1.setText("YOUR NAME");

        jLabel2.setFont(new java.awt.Font("Noto Sans", 3, 14)); // NOI18N
        jLabel2.setText("AGE GROUP");

        nametf.setFont(new java.awt.Font("Noto Sans", 3, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Noto Sans", 3, 14)); // NOI18N
        jLabel3.setText("Studying in");

        jLabel4.setFont(new java.awt.Font("Noto Sans", 3, 14)); // NOI18N
        jLabel4.setText("Favourits subject");

        jLabel5.setFont(new java.awt.Font("Noto Sans", 3, 14)); // NOI18N
        jLabel5.setText("How Do u like to spend ur free time ?");

        agebg.add(bt12);
        bt12.setFont(new java.awt.Font("Noto Sans", 3, 14)); // NOI18N
        bt12.setText("Below 12");

        agebg.add(bt14);
        bt14.setFont(new java.awt.Font("Noto Sans", 3, 14)); // NOI18N
        bt14.setText("12 to 14");

        agebg.add(bt18);
        bt18.setFont(new java.awt.Font("Noto Sans", 3, 14)); // NOI18N
        bt18.setText("16 to 18");

        agebg.add(bta18);
        bta18.setFont(new java.awt.Font("Noto Sans", 3, 14)); // NOI18N
        bta18.setText("Above 18");

        agebg.add(bt16);
        bt16.setFont(new java.awt.Font("Noto Sans", 3, 14)); // NOI18N
        bt16.setText("14 to -16");

        edulist.setFont(new java.awt.Font("Noto Sans", 2, 14)); // NOI18N
        edulist.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Primary Class", "Middle Class", "Secondary Classes", "Sr Secondary Classes", "College", " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(edulist);

        tvcb.setFont(new java.awt.Font("Noto Sans", 3, 14)); // NOI18N
        tvcb.setText("Watching T.V");

        artcb.setFont(new java.awt.Font("Noto Sans", 3, 14)); // NOI18N
        artcb.setText("Creative arts");
        artcb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                artcbActionPerformed(evt);
            }
        });

        wmcb.setFont(new java.awt.Font("Noto Sans", 3, 14)); // NOI18N
        wmcb.setText("Watching movies");

        advcb.setFont(new java.awt.Font("Noto Sans", 3, 14)); // NOI18N
        advcb.setText("Adventures sports");

        cookcb.setFont(new java.awt.Font("Noto Sans", 3, 14)); // NOI18N
        cookcb.setText("Cooking");

        indcb.setFont(new java.awt.Font("Noto Sans", 3, 14)); // NOI18N
        indcb.setText("Indoor games");

        playcb.setFont(new java.awt.Font("Noto Sans", 3, 14)); // NOI18N
        playcb.setText("Playing sports");

        othercb.setFont(new java.awt.Font("Noto Sans", 3, 14)); // NOI18N
        othercb.setText("OTHERS");

        subbtn.setFont(new java.awt.Font("Noto Sans", 3, 14)); // NOI18N
        subbtn.setText("SUBMIT");
        subbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subbtnActionPerformed(evt);
            }
        });

        canbtn.setFont(new java.awt.Font("Noto Sans", 3, 14)); // NOI18N
        canbtn.setText("CANCLE");
        canbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canbtnActionPerformed(evt);
            }
        });

        sublist.setFont(new java.awt.Font("Noto Sans", 2, 14)); // NOI18N
        sublist.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Mathematics", "Languages", "Core Science", "Art Sub", "Humanities Sub", "Technology Sub" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(sublist);

        jLabel6.setFont(new java.awt.Font("Rekha", 3, 18)); // NOI18N
        jLabel6.setText("HUMAN RESOURCE DEPARTMENT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(artcb)
                            .addComponent(tvcb))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(advcb)
                            .addComponent(wmcb))
                        .addGap(35, 35, 35)
                        .addComponent(cookcb))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel5)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bt12)
                                        .addGap(24, 24, 24)
                                        .addComponent(bt14))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(77, 77, 77)
                                        .addComponent(subbtn)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addComponent(canbtn))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(2, 2, 2)
                                                .addComponent(bt16)
                                                .addGap(31, 31, 31)
                                                .addComponent(bt18))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(indcb)
                                                .addGap(52, 52, 52)
                                                .addComponent(othercb))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(116, 116, 116)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addComponent(nametf, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(360, 360, 360)
                                .addComponent(playcb)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bta18)
                        .addGap(232, 232, 232))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nametf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bta18)
                    .addComponent(bt18)
                    .addComponent(bt16)
                    .addComponent(bt14)
                    .addComponent(bt12)
                    .addComponent(jLabel2))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tvcb)
                    .addComponent(wmcb)
                    .addComponent(cookcb)
                    .addComponent(playcb))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(indcb)
                    .addComponent(advcb)
                    .addComponent(artcb)
                    .addComponent(othercb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subbtn)
                    .addComponent(canbtn))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void artcbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_artcbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_artcbActionPerformed

    private void canbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canbtnActionPerformed
           nametf.setText("");
           edulist.clearSelection();
           sublist.clearSelection();
           tvcb.setSelected(false);
           wmcb.setSelected(false);
           artcb.setSelected(false);
           playcb.setSelected(false);
           cookcb.setSelected(false);
           advcb.setSelected(false);
           indcb.setSelected(false);
           othercb.setSelected(false);
           
    }//GEN-LAST:event_canbtnActionPerformed

    private void subbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subbtnActionPerformed
       dispose();
    }//GEN-LAST:event_subbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HRDepartment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HRDepartment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HRDepartment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HRDepartment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HRDepartment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox advcb;
    private javax.swing.ButtonGroup agebg;
    private javax.swing.JCheckBox artcb;
    private javax.swing.JRadioButton bt12;
    private javax.swing.JRadioButton bt14;
    private javax.swing.JRadioButton bt16;
    private javax.swing.JRadioButton bt18;
    private javax.swing.JRadioButton bta18;
    private javax.swing.JButton canbtn;
    private javax.swing.JCheckBox cookcb;
    private javax.swing.JList edulist;
    private javax.swing.JCheckBox indcb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nametf;
    private javax.swing.JCheckBox othercb;
    private javax.swing.JCheckBox playcb;
    private javax.swing.JButton subbtn;
    private javax.swing.JList sublist;
    private javax.swing.JCheckBox tvcb;
    private javax.swing.JCheckBox wmcb;
    // End of variables declaration//GEN-END:variables
}
