import javax.swing.ImageIcon;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mishra
 */
public class Solar_System extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Solar_System() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        SSList = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        InfoTA = new javax.swing.JTextArea();
        Image = new javax.swing.JLabel();
        FactLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SSList.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SSList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Asteroids", "Earth", "Jupiter", "Mars", "Mercury", "Meteor", "Neptune", "Saturn", "Sun", "Uranus", "Venus" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        SSList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        SSList.setVisibleRowCount(13);
        SSList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                SSListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(SSList);

        InfoTA.setEditable(false);
        InfoTA.setColumns(20);
        InfoTA.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        InfoTA.setLineWrap(true);
        InfoTA.setRows(10);
        InfoTA.setWrapStyleWord(true);
        jScrollPane2.setViewportView(InfoTA);

        Image.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        FactLbl.setText(" ");
        FactLbl.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(FactLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
                        .addGap(57, 57, 57)
                        .addComponent(Image)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FactLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                            .addComponent(Image))
                        .addGap(16, 16, 16)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SSListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_SSListValueChanged
        // TODO add your handling code here:
        int i = SSList.getSelectedIndex();
        switch(i){
            case 0 : FactLbl.setText("<html>The biggest asteroid is Ceres. <br> It is about 600 miles (960 km) around.");
                     InfoTA.setText("The biggest space rocks are asteroids. Asteroids are made up of rock and iron like the four planets closest to our Sun. Different from comets; asteroids are more like planets and moons. Scientists often call asteroids minor planets.");
                     Image.setIcon( new ImageIcon ("\\E:\\DURGESH\\New folder\\asteroid.gif"));
                     break;
            case 1 : FactLbl.setText("<html> The four seasons are a result of Earth's axis of rotation <br> being tilted more than 23 degrees.");
                     InfoTA.setText("Earth is the third planet from the Sun and the fifth largest in the solar system. It is the only planet in our solar system known to harbour life. Earth's diameter is just a few hundred kilometres larger than that of Venus.");
                     Image.setIcon( new ImageIcon ("\\E:\\DURGESH\\New folder\\earth.gif"));
                     break;
            case 2 : FactLbl.setText("<html>Jupiter’s moon Ganymede is the largest planetary moon. <br>Ganymede is the only moon in the solar system known to have its own magnetic field.");
                     InfoTA.setText("Jupiter is the Fifth planet from the sun. The most massive planet in our solar system, with four planet-sized moons and many smaller moons – in total 49 officially named moons.");
                     Image.setIcon( new ImageIcon ("\\E:\\DURGESH\\New folder\\jupiter.gif"));
                     break;
            case 3 : FactLbl.setText("<html>Mars has polar ice caps that grow and <br>recede with the change of seasons.");
                     InfoTA.setText("The red planet Mars is a small rocky body once thought to be very Earth-like. It is Fourth planet from the sun. ");
                     Image.setIcon( new ImageIcon ("\\E:\\DURGESH\\New folder\\mars.gif"));
                     break;
            case 4 : FactLbl.setText("<html>Mercury, like Earth, has a global internal magnetic field. <br>But Mars and Venus do not have any such field.");
                     InfoTA.setText("Mercury is an extreme planet: the smallest, the densest, nearest to the sun and  the one with the oldest surface, the one with the largest daily variations in surface temperature, and the least explored.");
                     Image.setIcon( new ImageIcon ("\\E:\\DURGESH\\New folder\\merc.gif"));
                     break;
            case 5 : FactLbl.setText("<html>Scientists estimate that 1,000 tons to more than 10,000 tons of <br> meteoritic material (very tiny; dust like) falls on the Earth each day.");
                     InfoTA.setText("Shooting stars or meteors are bits of material falling through Earth's atmosphere; they are heated to incandescence by the friction of the air. The bright trails as they are coming through the Earth's atmosphere are termed meteors, and these chunks as they are hurtling through space are called meteoroids.");
                     Image.setIcon( new ImageIcon ("\\E:\\DURGESH\\New folder\\meteor.gif"));
                     break;
            case 6 : FactLbl.setText("<html>Owing to Pluto's unusual elliptical orbit, Neptune is actually <br> the farthest planet (including dwarf planets) from the Sun for a 20-year period out of every 248 Earth years.");
                     InfoTA.setText("The eighth planet from the Sun, Neptune was the first planet located through mathematical predictions rather than through regular observations of the sky.");
                     Image.setIcon( new ImageIcon ("\\E:\\DURGESH\\New folder\\neptune.gif"));
                     break;
            case 7 : FactLbl.setText("<html>Saturn's rings help us learn how the solar system was before planets formed. <br> Its largest moon, Titan, shows us an atmosphere like Earth's before life developed.");
                     InfoTA.setText("Sixth planet from the sun, Saturn is made mostly of hydrogen and helium. Its volume is 755 times greater than that of Earth.");
                     Image.setIcon( new ImageIcon ("\\E:\\DURGESH\\New folder\\saturn.gif"));
                     break;
            case 8 : FactLbl.setText("<html>The Sun is at a mean distance from earth of 149.60 million kilometres (92.96 million miles). <br>This distance is known as an astronomical unit (abbreviated AU), and sets the scale for measuring distances all across the solar system.");
                     InfoTA.setText("Our solar system's star, the Sun, is our nearest star. The Sun is the source of most of the light and heat in our solar system.");
                     Image.setIcon( new ImageIcon ("\\E:\\DURGESH\\New folder\\sun.gif"));
                     break;
            case 9 : FactLbl.setText("<html> The Uranus was the first planet found with <br> the aid of a telescope.");
                     InfoTA.setText("Uranus is the seventh planet from the sun. Its atmosphere is composed primarily of hydrogen and helium, with a small amount of methane and traces of water and ammonia. Uranus gets its blue-green colour from methane gas.");
                     Image.setIcon( new ImageIcon ("\\E:\\DURGESH\\New folder\\uranus.gif"));
                     break;
            case 10 : FactLbl.setText("<html>Venus rotates retrograde (east to west) compared with Earth's prograde (west to east) rotation. <br> Seen from Venus, the Sun would rise in the west and set in the east.");
                     InfoTA.setText("Second planet from the sun, Venus is similar to earth in size, mass, composition, and distance from the Sun. ");
                     Image.setIcon( new ImageIcon ("\\E:\\DURGESH\\New folder\\venus.gif"));
                     break;
        }
    }//GEN-LAST:event_SSListValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Solar_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Solar_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Solar_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Solar_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Solar_System().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FactLbl;
    private javax.swing.JLabel Image;
    private javax.swing.JTextArea InfoTA;
    private javax.swing.JList SSList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
