import java.sql.*;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mishra
 */
public class Student_Record extends javax.swing.JFrame {

    /**
     * Creates new form rECORD
     */
    public Student_Record() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        stf = new javax.swing.JTextField();
        ntf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ctf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        mrb = new javax.swing.JRadioButton();
        frb = new javax.swing.JRadioButton();
        delbtn = new javax.swing.JButton();
        savebtn = new javax.swing.JButton();
        sbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbtn.setFont(new java.awt.Font("Snap ITC", 3, 15)); // NOI18N
        cbtn.setForeground(new java.awt.Color(102, 0, 102));
        cbtn.setText("Clear");
        cbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Viner Hand ITC", 3, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 51));
        jLabel1.setText("STUDENTS RECORD");

        jLabel6.setFont(new java.awt.Font("Bell MT", 3, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 51, 0));
        jLabel6.setText("SNO");

        stf.setFont(new java.awt.Font("Bell MT", 3, 15)); // NOI18N
        stf.setForeground(new java.awt.Color(204, 51, 0));
        stf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stfActionPerformed(evt);
            }
        });

        ntf.setFont(new java.awt.Font("Bell MT", 3, 15)); // NOI18N
        ntf.setForeground(new java.awt.Color(204, 51, 0));
        ntf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ntfActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Bell MT", 3, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 51, 0));
        jLabel3.setText("CLASS");

        jLabel2.setFont(new java.awt.Font("Bell MT", 3, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 51, 0));
        jLabel2.setText("NAME");

        ctf.setFont(new java.awt.Font("Bell MT", 3, 15)); // NOI18N
        ctf.setForeground(new java.awt.Color(204, 51, 0));
        ctf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctfActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Bell MT", 3, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 51, 0));
        jLabel5.setText("GENDER");

        mrb.setFont(new java.awt.Font("Bell MT", 3, 15)); // NOI18N
        mrb.setForeground(new java.awt.Color(204, 51, 0));
        mrb.setText("MALE");
        mrb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mrbActionPerformed(evt);
            }
        });

        frb.setFont(new java.awt.Font("Bell MT", 3, 15)); // NOI18N
        frb.setForeground(new java.awt.Color(204, 51, 0));
        frb.setText("FEMALE");
        frb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frbActionPerformed(evt);
            }
        });

        delbtn.setFont(new java.awt.Font("Snap ITC", 3, 15)); // NOI18N
        delbtn.setForeground(new java.awt.Color(102, 0, 102));
        delbtn.setText("DELETE");
        delbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delbtnActionPerformed(evt);
            }
        });

        savebtn.setFont(new java.awt.Font("Snap ITC", 3, 15)); // NOI18N
        savebtn.setForeground(new java.awt.Color(102, 0, 102));
        savebtn.setText("SAVE");
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });

        sbtn.setFont(new java.awt.Font("Snap ITC", 3, 15)); // NOI18N
        sbtn.setForeground(new java.awt.Color(102, 0, 102));
        sbtn.setText("SEARCH");
        sbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(savebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 58, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ctf, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(132, 132, 132)
                                    .addComponent(frb))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(mrb)
                                    .addGap(154, 154, 154)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sbtn)
                                .addGap(74, 74, 74)
                                .addComponent(delbtn))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(stf, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ntf, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(72, 72, 72)
                                .addComponent(cbtn)))
                        .addGap(90, 90, 90)))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(stf, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(ntf, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 21, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(ctf, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mrb)
                    .addComponent(frb)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(savebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbtnActionPerformed
        stf.setText("");
        ntf.setText("");
        ctf.setText("");
        mrb.setSelected(false);
        frb.setSelected(false);
    }//GEN-LAST:event_cbtnActionPerformed

    private void stfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stfActionPerformed

    private void ntfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ntfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ntfActionPerformed

    private void ctfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctfActionPerformed

    private void mrbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mrbActionPerformed
        int gender = 0;
        if(mrb.isSelected()==true)
        {
            gender = 1;
        }
        else
        {
            gender = 2;
        }
    }//GEN-LAST:event_mrbActionPerformed

    private void frbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frbActionPerformed
        int gender = 0;
        if(frb.isSelected()==true)
        {
            gender = 1;
        }
        else
        {
            gender = 2;
        }
    }//GEN-LAST:event_frbActionPerformed

    private void delbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delbtnActionPerformed
        try
        {
            Class.forName("java.sql.Driver");
            Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/sfs","root","a");
            Statement stmt = con.createStatement();
            int Sno = Integer.parseInt(stf.getText());
            String query = "Delete from stubasic where Sno="+Sno+";";
            stmt.executeUpdate(query);
            stf.setText("");
            ntf.setText("");
            ctf.setText("");
            mrb.setSelected(false);
            frb.setSelected(false);
            JOptionPane.showMessageDialog(null,"record deleted");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"error in connectivity");
        }
    }//GEN-LAST:event_delbtnActionPerformed

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        try
        {
            Class.forName("java.sql.Driver");
            Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/sfs","root","a");
            Statement stmt = con.createStatement();
            int Sno = Integer.parseInt(stf.getText());
            String Name= ntf.getText();
            int Clas = Integer.parseInt(ctf.getText());
            String Gender = "0";
            if(mrb.isSelected())
            Gender = "Male";
            if(frb.isSelected())
            Gender = "Female";
            String query = "Insert into stubasic values("+Sno+",'"+Name+"',"+Clas+",'"+Gender+"');";
            stmt.executeUpdate(query);
            JOptionPane.showMessageDialog(null,"record saved");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"error in connectivity");
        }
    }//GEN-LAST:event_savebtnActionPerformed

    private void sbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbtnActionPerformed
        try
        {
            Class.forName("java.sql.Driver");
            Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/sfs","root","a");
            Statement stmt = con.createStatement();
            int Sno = Integer.parseInt(stf.getText());
            String query = "Select* from stubasic where Sno="+Sno+";";
            stmt.executeUpdate(query);
            ResultSet rs=stmt.executeQuery(query);
            while(rs.next())
            {
                String Name=rs.getString("Name");
                int Clas=rs.getInt("Clas");
                String Gender=rs.getString("Gender");
                String Male =null;
                if (Gender==Male)
                mrb.setSelected(true);
                else
                frb.setSelected(true);
                ntf.setText(""+Name);
                ctf.setText(""+Clas);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"error in connectivity");
        }
    }//GEN-LAST:event_sbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student_Record.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student_Record.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student_Record.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student_Record.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student_Record().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cbtn;
    private javax.swing.JTextField ctf;
    private javax.swing.JButton delbtn;
    private javax.swing.JRadioButton frb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton mrb;
    private javax.swing.JTextField ntf;
    private javax.swing.JButton savebtn;
    private javax.swing.JButton sbtn;
    private javax.swing.JTextField stf;
    // End of variables declaration//GEN-END:variables
}
